//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockController.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ELEKTRASHARE\\Shares\\VendorStock\\VendorFiles")]
        public string target_Stock {
            get {
                return ((string)(this["target_Stock"]));
            }
            set {
                this["target_Stock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Gareev\\Documents\\Остатки\\Обработка")]
        public string self_Stock {
            get {
                return ((string)(this["self_Stock"]));
            }
            set {
                this["self_Stock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Gareev\\Documents\\Остатки\\StockData.csv")]
        public string file_StocksList {
            get {
                return ((string)(this["file_StocksList"]));
            }
            set {
                this["file_StocksList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ELEKTRASHARE\\Shares\\VendorStock\\Archives")]
        public string archive_Stock {
            get {
                return ((string)(this["archive_Stock"]));
            }
            set {
                this["archive_Stock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2017-06-06")]
        public global::System.DateTime lastWorkDate {
            get {
                return ((global::System.DateTime)(this["lastWorkDate"]));
            }
            set {
                this["lastWorkDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool first_Launch {
            get {
                return ((bool)(this["first_Launch"]));
            }
            set {
                this["first_Launch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color color_Correct {
            get {
                return ((global::System.Drawing.Color)(this["color_Correct"]));
            }
            set {
                this["color_Correct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color color_Incorrect {
            get {
                return ((global::System.Drawing.Color)(this["color_Incorrect"]));
            }
            set {
                this["color_Incorrect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color color_Nothing {
            get {
                return ((global::System.Drawing.Color)(this["color_Nothing"]));
            }
            set {
                this["color_Nothing"] = value;
            }
        }
    }
}
